# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c15074cd15ebdbb6ee2fb516b310b2f3fd285ac673886fb87a61e6ebc9a2c5416d3d5f93ae5adb915c7d526993ca8632ebb184106ab3bc7b6119fbefdc309398

test:
  secret_key_base: 7897dbb629806a4f11765a931f9e06f1f5ff475ccf0dd6d26cfd36f1c827294eacf575bd0c5fc7af4db7b4a9a2e43e952b2122943ea36d72dfe7c83d6fd49dcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
